---
name: Node.js CI

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - README.md
      - .github/**
      - locales/**
      - sounds/**
      - package.json
      - addons/**
      - .gitignore
      - docker-compose.yml
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  CommitLint:
    name: Lint Commit Messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: rm tsconfig.json
      - uses: wagoid/commitlint-github-action@v6.1.1

  quality:
    name: Build the Node
    needs:
      - CommitLint
    runs-on: ubuntu-latest
    steps:
      # -----------------------------------------------------------------------
      #                    Check out The Repository
      # -----------------------------------------------------------------------
      - name: 💾 Check out repository
        uses: actions/checkout@v4

      # -----------------------------------------------------------------------
      #                    Install Node.js and pnpm
      # -----------------------------------------------------------------------
      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: pnpm/action-setup@v3
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      # -----------------------------------------------------------------------
      #                    Cache dependencies
      # -----------------------------------------------------------------------
      - name: Get PNPM Store Directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: Setup PNPM Cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      # -----------------------------------------------------------------------
      #                    Install dependencies
      # -----------------------------------------------------------------------
      - name: Install dependencies
        run: pnpm i

      # -----------------------------------------------------------------------
      #                    Build and lint
      # -----------------------------------------------------------------------
      - name: Build
        run: pnpm build
      - name: Lint
        run: pnpm lint

      # -----------------------------------------------------------------------
      #                    Run tests
      # -----------------------------------------------------------------------
      - name: Test
        run: pnpm test

      # -----------------------------------------------------------------------
      #                    Upload coverage
      # -----------------------------------------------------------------------
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    needs:
      - CommitLint
      - quality
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
